// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: protos/blog/v1/blog.proto

package blog

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UUID represents a universally unique identifier
type UUID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The string representation of the UUID
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Blog represents a blog with title, content, and comments
type Blog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the blog
	Id *UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Title of the blog
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Content of the blog
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Comments on the blog
	Comments      []*Comment `protobuf:"bytes,6,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blog) Reset() {
	*x = Blog{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog) ProtoMessage() {}

func (x *Blog) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog.ProtoReflect.Descriptor instead.
func (*Blog) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{1}
}

func (x *Blog) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Blog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Blog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Blog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Blog) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Blog) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

// Comment represents a comment on a blog
type Comment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the comment
	Id *UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Content of the comment
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Author of the comment
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	// Creation timestamp
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{2}
}

func (x *Comment) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Request to create a new blog
type CreateReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Title of the blog post
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Content of the blog post
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Response for creating a blog
type CreateResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the created blog
	Id            *UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResp) Reset() {
	*x = CreateResp{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResp) ProtoMessage() {}

func (x *CreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResp.ProtoReflect.Descriptor instead.
func (*CreateResp) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{4}
}

func (x *CreateResp) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

// Request to get a blog by ID
type GetReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the blog to retrieve
	Id            *UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{5}
}

func (x *GetReq) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

// Response for getting a blog
type GetResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The retrieved blog
	Blog          *Blog `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{6}
}

func (x *GetResp) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

// Request to update a blog
type UpdateReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the blog to update
	Id *UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// New title for the blog (optional)
	Title *string `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// New content for the blog (optional)
	Content       *string `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateReq) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateReq) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateReq) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

// Request to delete a blog
type DeleteReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the blog to delete
	Id            *UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteReq) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

// Request to list blogs with pagination
type ListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of blogs to return
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token for pagination
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{9}
}

func (x *ListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListReq) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response for listing blogs with their titles and comment counts
type ListResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of blog entries with title and comment count
	Blogs []*BlogSummary `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	// Token for retrieving the next page
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResp) Reset() {
	*x = ListResp{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResp) ProtoMessage() {}

func (x *ListResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResp.ProtoReflect.Descriptor instead.
func (*ListResp) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{10}
}

func (x *ListResp) GetBlogs() []*BlogSummary {
	if x != nil {
		return x.Blogs
	}
	return nil
}

func (x *ListResp) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Summary of a blog containing title and comment count
type BlogSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the blog
	Id *UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Title of the blog
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Number of comments on the blog
	CommentCount  int32 `protobuf:"varint,3,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogSummary) Reset() {
	*x = BlogSummary{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogSummary) ProtoMessage() {}

func (x *BlogSummary) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogSummary.ProtoReflect.Descriptor instead.
func (*BlogSummary) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{11}
}

func (x *BlogSummary) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BlogSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BlogSummary) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

// Request to add a comment to a blog
type AddCommentReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the blog to comment on
	Id *UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Content of the comment
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Author of the comment
	Author        string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentReq) Reset() {
	*x = AddCommentReq{}
	mi := &file_protos_blog_v1_blog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentReq) ProtoMessage() {}

func (x *AddCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blog_v1_blog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentReq.ProtoReflect.Descriptor instead.
func (*AddCommentReq) Descriptor() ([]byte, []int) {
	return file_protos_blog_v1_blog_proto_rawDescGZIP(), []int{12}
}

func (x *AddCommentReq) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AddCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddCommentReq) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

var File_protos_blog_v1_blog_proto protoreflect.FileDescriptor

const file_protos_blog_v1_blog_proto_rawDesc = "" +
	"\n" +
	"\x19protos/blog/v1/blog.proto\x12\ablog.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"c\n" +
	"\x04UUID\x12[\n" +
	"\x05value\x18\x01 \x01(\tBE\xbaHBr@2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$R\x05value\"\xa6\x02\n" +
	"\x04Blog\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.blog.v1.UUIDR\x02id\x125\n" +
	"\x05title\x18\x02 \x01(\tB\x1f\xbaH\x1cr\x1a\x10\x01\x18d2\x14^[\\w\\s\\-\\.,:;!?()]+$R\x05title\x12$\n" +
	"\acontent\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x90NR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12,\n" +
	"\bcomments\x18\x06 \x03(\v2\x10.blog.v1.CommentR\bcomments\"\xac\x01\n" +
	"\aComment\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.blog.v1.UUIDR\x02id\x12$\n" +
	"\acontent\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xe8\aR\acontent\x12!\n" +
	"\x06author\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\x06author\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"h\n" +
	"\tCreateReq\x125\n" +
	"\x05title\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1a\x10\x01\x18d2\x14^[\\w\\s\\-\\.,:;!?()]+$R\x05title\x12$\n" +
	"\acontent\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x90NR\acontent\"+\n" +
	"\n" +
	"CreateResp\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.blog.v1.UUIDR\x02id\"'\n" +
	"\x06GetReq\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.blog.v1.UUIDR\x02id\",\n" +
	"\aGetResp\x12!\n" +
	"\x04blog\x18\x01 \x01(\v2\r.blog.v1.BlogR\x04blog\"\xa7\x01\n" +
	"\tUpdateReq\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.blog.v1.UUIDR\x02id\x12:\n" +
	"\x05title\x18\x02 \x01(\tB\x1f\xbaH\x1cr\x1a\x10\x01\x18d2\x14^[\\w\\s\\-\\.,:;!?()]+$H\x00R\x05title\x88\x01\x01\x12)\n" +
	"\acontent\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x90NH\x01R\acontent\x88\x01\x01B\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_content\"*\n" +
	"\tDeleteReq\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.blog.v1.UUIDR\x02id\"P\n" +
	"\aListReq\x12&\n" +
	"\tpage_size\x18\x01 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d \x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"^\n" +
	"\bListResp\x12*\n" +
	"\x05blogs\x18\x01 \x03(\v2\x14.blog.v1.BlogSummaryR\x05blogs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"g\n" +
	"\vBlogSummary\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.blog.v1.UUIDR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rcomment_count\x18\x03 \x01(\x05R\fcommentCount\"w\n" +
	"\rAddCommentReq\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.blog.v1.UUIDR\x02id\x12$\n" +
	"\acontent\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xe8\aR\acontent\x12!\n" +
	"\x06author\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\x06author2\xea\x03\n" +
	"\x05Blogs\x12G\n" +
	"\x06Create\x12\x12.blog.v1.CreateReq\x1a\x13.blog.v1.CreateResp\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/posts\x12F\n" +
	"\x03Get\x12\x0f.blog.v1.GetReq\x1a\x10.blog.v1.GetResp\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/posts/{id.value}\x12U\n" +
	"\x06Update\x12\x12.blog.v1.UpdateReq\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*2\x14/v1/posts/{id.value}\x12R\n" +
	"\x06Delete\x12\x12.blog.v1.DeleteReq\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/posts/{id.value}\x12>\n" +
	"\x04List\x12\x10.blog.v1.ListReq\x1a\x11.blog.v1.ListResp\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/posts\x12e\n" +
	"\n" +
	"AddComment\x12\x16.blog.v1.AddCommentReq\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/posts/{id.value}/commentB/Z-github.com/agruetz/prosigliere/protos/v1/blogb\x06proto3"

var (
	file_protos_blog_v1_blog_proto_rawDescOnce sync.Once
	file_protos_blog_v1_blog_proto_rawDescData []byte
)

func file_protos_blog_v1_blog_proto_rawDescGZIP() []byte {
	file_protos_blog_v1_blog_proto_rawDescOnce.Do(func() {
		file_protos_blog_v1_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_blog_v1_blog_proto_rawDesc), len(file_protos_blog_v1_blog_proto_rawDesc)))
	})
	return file_protos_blog_v1_blog_proto_rawDescData
}

var file_protos_blog_v1_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protos_blog_v1_blog_proto_goTypes = []any{
	(*UUID)(nil),                  // 0: blog.v1.UUID
	(*Blog)(nil),                  // 1: blog.v1.Blog
	(*Comment)(nil),               // 2: blog.v1.Comment
	(*CreateReq)(nil),             // 3: blog.v1.CreateReq
	(*CreateResp)(nil),            // 4: blog.v1.CreateResp
	(*GetReq)(nil),                // 5: blog.v1.GetReq
	(*GetResp)(nil),               // 6: blog.v1.GetResp
	(*UpdateReq)(nil),             // 7: blog.v1.UpdateReq
	(*DeleteReq)(nil),             // 8: blog.v1.DeleteReq
	(*ListReq)(nil),               // 9: blog.v1.ListReq
	(*ListResp)(nil),              // 10: blog.v1.ListResp
	(*BlogSummary)(nil),           // 11: blog.v1.BlogSummary
	(*AddCommentReq)(nil),         // 12: blog.v1.AddCommentReq
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_protos_blog_v1_blog_proto_depIdxs = []int32{
	0,  // 0: blog.v1.Blog.id:type_name -> blog.v1.UUID
	13, // 1: blog.v1.Blog.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: blog.v1.Blog.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: blog.v1.Blog.comments:type_name -> blog.v1.Comment
	0,  // 4: blog.v1.Comment.id:type_name -> blog.v1.UUID
	13, // 5: blog.v1.Comment.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: blog.v1.CreateResp.id:type_name -> blog.v1.UUID
	0,  // 7: blog.v1.GetReq.id:type_name -> blog.v1.UUID
	1,  // 8: blog.v1.GetResp.blog:type_name -> blog.v1.Blog
	0,  // 9: blog.v1.UpdateReq.id:type_name -> blog.v1.UUID
	0,  // 10: blog.v1.DeleteReq.id:type_name -> blog.v1.UUID
	11, // 11: blog.v1.ListResp.blogs:type_name -> blog.v1.BlogSummary
	0,  // 12: blog.v1.BlogSummary.id:type_name -> blog.v1.UUID
	0,  // 13: blog.v1.AddCommentReq.id:type_name -> blog.v1.UUID
	3,  // 14: blog.v1.Blogs.Create:input_type -> blog.v1.CreateReq
	5,  // 15: blog.v1.Blogs.Get:input_type -> blog.v1.GetReq
	7,  // 16: blog.v1.Blogs.Update:input_type -> blog.v1.UpdateReq
	8,  // 17: blog.v1.Blogs.Delete:input_type -> blog.v1.DeleteReq
	9,  // 18: blog.v1.Blogs.List:input_type -> blog.v1.ListReq
	12, // 19: blog.v1.Blogs.AddComment:input_type -> blog.v1.AddCommentReq
	4,  // 20: blog.v1.Blogs.Create:output_type -> blog.v1.CreateResp
	6,  // 21: blog.v1.Blogs.Get:output_type -> blog.v1.GetResp
	14, // 22: blog.v1.Blogs.Update:output_type -> google.protobuf.Empty
	14, // 23: blog.v1.Blogs.Delete:output_type -> google.protobuf.Empty
	10, // 24: blog.v1.Blogs.List:output_type -> blog.v1.ListResp
	14, // 25: blog.v1.Blogs.AddComment:output_type -> google.protobuf.Empty
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protos_blog_v1_blog_proto_init() }
func file_protos_blog_v1_blog_proto_init() {
	if File_protos_blog_v1_blog_proto != nil {
		return
	}
	file_protos_blog_v1_blog_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_blog_v1_blog_proto_rawDesc), len(file_protos_blog_v1_blog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_blog_v1_blog_proto_goTypes,
		DependencyIndexes: file_protos_blog_v1_blog_proto_depIdxs,
		MessageInfos:      file_protos_blog_v1_blog_proto_msgTypes,
	}.Build()
	File_protos_blog_v1_blog_proto = out.File
	file_protos_blog_v1_blog_proto_goTypes = nil
	file_protos_blog_v1_blog_proto_depIdxs = nil
}
